'use client';
import React, { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowLeft, FileText, Clock, Hash, Layers,
  Lightbulb, CheckSquare, Tag, Send, Bot, User,
  Download, AlertCircle
} from 'lucide-react';

interface Insight {
  point: string;
  importance: 'high' | 'medium' | 'low';
  page?: number;
}

interface Analysis {
  title: string;
  summary: string;
  keyInsights: Insight[];
  actionItems: string[];
  themes: string[];
  documentType: string;
  readingTime: string;
  wordCount: number;
}

interface Payload {
  analysis: Analysis;
  rawText: string;
  numPages: number;
  fileName: string;
}

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

const importanceConfig = {
  high:   { label: 'High',   cls: 'badge badge-high' },
  medium: { label: 'Medium', cls: 'badge badge-medium' },
  low:    { label: 'Low',    cls: 'badge badge-low' },
};

export default function AnalyzePage() {
  const router = useRouter();
  const [payload, setPayload] = useState<Payload | null>(null);
  const [activeTab, setActiveTab] = useState<'summary' | 'insights' | 'actions'>('summary');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const stored = localStorage.getItem('smartread_last_analysis');
    if (!stored) { router.push('/'); return; }
    try { setPayload(JSON.parse(stored)); }
    catch { router.push('/'); }
  }, [router]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, chatLoading]);

  async function sendMessage() {
    if (!input.trim() || !payload || chatLoading) return;

    const userMsg: ChatMessage = { role: 'user', content: input.trim() };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput('');
    setChatLoading(true);

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: newMessages,
          documentContext: payload.rawText,
          documentTitle: payload.analysis.title,
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setMessages([...newMessages, { role: 'assistant', content: data.reply }]);
    } catch (err) {
      setMessages([...newMessages, {
        role: 'assistant',
        content: '⚠️ Sorry, something went wrong. Please try again.',
      }]);
    } finally {
      setChatLoading(false);
    }
  }

  function downloadMarkdown() {
    if (!payload) return;
    const { analysis, fileName } = payload;
    const md = [
      `# ${analysis.title}`,
      `> ${analysis.documentType} · ${analysis.readingTime} · ${analysis.wordCount.toLocaleString()} words`,
      '',
      '## Summary',
      analysis.summary,
      '',
      '## Key Insights',
      ...analysis.keyInsights.map(
        (i) => `- **[${i.importance.toUpperCase()}]** ${i.point}${i.page ? ` _(p. ${i.page})_` : ''}`
      ),
      '',
      '## Action Items',
      ...analysis.actionItems.map((a) => `- [ ] ${a}`),
      '',
      '## Themes',
      analysis.themes.join(', '),
      '',
      `---`,
      `*Generated by SmartRead from ${fileName}*`,
    ].join('\n');

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${analysis.title.replace(/\s+/g, '_')}_analysis.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (!payload) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-[var(--text-muted)] animate-pulse">Loading analysis…</div>
      </div>
    );
  }

  const { analysis, numPages, fileName } = payload;

  const tabs = [
    { id: 'summary' as const,  label: 'Summary',   icon: FileText },
    { id: 'insights' as const, label: 'Insights',  icon: Lightbulb },
    { id: 'actions' as const,  label: 'Actions',   icon: CheckSquare },
  ];

  return (
    <main className="min-h-screen py-8">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between mb-8"
      >
        <button
          onClick={() => router.push('/')}
          className="flex items-center gap-2 text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors text-sm"
        >
          <ArrowLeft size={16} /> New Document
        </button>
        <button
          onClick={downloadMarkdown}
          className="flex items-center gap-2 px-4 py-2 rounded-xl border border-[var(--border)] hover:border-[var(--border-hover)] text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-all"
        >
          <Download size={14} /> Export Markdown
        </button>
      </motion.div>

      {/* Doc title + meta */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="mb-8"
      >
        <h1 className="font-syne text-3xl sm:text-4xl font-extrabold mb-3 gradient-text">
          {analysis.title}
        </h1>
        <div className="flex flex-wrap items-center gap-4 text-[var(--text-muted)] text-sm">
          <span className="flex items-center gap-1.5"><FileText size={13} /> {fileName}</span>
          <span className="flex items-center gap-1.5"><Layers size={13} /> {numPages} pages</span>
          <span className="flex items-center gap-1.5"><Clock size={13} /> {analysis.readingTime}</span>
          <span className="flex items-center gap-1.5"><Hash size={13} /> {analysis.wordCount?.toLocaleString()} words</span>
          <span className="badge badge-theme capitalize">{analysis.documentType}</span>
        </div>
      </motion.div>

      {/* Themes row */}
      {analysis.themes?.length > 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.15 }}
          className="flex flex-wrap items-center gap-2 mb-8"
        >
          <Tag size={13} className="text-[var(--text-muted)]" />
          {analysis.themes.map((theme) => (
            <span key={theme} className="badge badge-theme">{theme}</span>
          ))}
        </motion.div>
      )}

      {/* Two-column layout */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* LEFT — Tabbed analysis */}
        <motion.div
          initial={{ opacity: 0, x: -12 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="card p-6 flex flex-col gap-4"
        >
          {/* Tabs */}
          <div className="flex gap-1 bg-white/[0.03] p-1 rounded-xl">
            {tabs.map(({ id, label, icon: Icon }) => (
              <button
                key={id}
                onClick={() => setActiveTab(id)}
                className={`flex-1 flex items-center justify-center gap-2 py-2 px-3 rounded-lg text-sm font-medium transition-all ${
                  activeTab === id
                    ? 'bg-[var(--accent)] text-white shadow-lg shadow-violet-500/25'
                    : 'text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
                }`}
              >
                <Icon size={13} />
                {label}
              </button>
            ))}
          </div>

          {/* Tab content */}
          <AnimatePresence mode="wait">
            {activeTab === 'summary' && (
              <motion.div
                key="summary"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                className="text-[var(--text-secondary)] text-sm leading-relaxed whitespace-pre-line"
              >
                {analysis.summary}
              </motion.div>
            )}

            {activeTab === 'insights' && (
              <motion.ul
                key="insights"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                className="space-y-3"
              >
                {analysis.keyInsights?.map((insight, i) => {
                  const cfg = importanceConfig[insight.importance] || importanceConfig.medium;
                  return (
                    <li key={i} className="flex flex-col gap-1.5 p-3 rounded-xl bg-white/[0.02] border border-[var(--border)]">
                      <div className="flex items-center justify-between gap-2">
                        <span className={cfg.cls}>{cfg.label}</span>
                        {insight.page && (
                          <span className="text-[var(--text-muted)] text-xs font-mono">p. {insight.page}</span>
                        )}
                      </div>
                      <p className="text-[var(--text-primary)] text-sm leading-relaxed">{insight.point}</p>
                    </li>
                  );
                })}
              </motion.ul>
            )}

            {activeTab === 'actions' && (
              <motion.ul
                key="actions"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                className="space-y-2"
              >
                {analysis.actionItems?.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.02] border border-[var(--border)] text-sm text-[var(--text-secondary)]">
                    <CheckSquare size={15} className="text-green-400 mt-0.5 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </motion.ul>
            )}
          </AnimatePresence>
        </motion.div>

        {/* RIGHT — Chat */}
        <motion.div
          initial={{ opacity: 0, x: 12 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.25 }}
          className="card p-6 flex flex-col h-[540px]"
        >
          <div className="flex items-center gap-2 mb-4">
            <Bot size={16} className="text-purple-400" />
            <span className="font-syne font-bold text-sm">Chat with Document</span>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto space-y-3 pr-1 mb-4">
            {messages.length === 0 && (
              <div className="h-full flex flex-col items-center justify-center text-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                  <Bot size={20} className="text-purple-400" />
                </div>
                <div>
                  <p className="text-[var(--text-primary)] text-sm font-medium mb-1">Ask anything about this document</p>
                  <p className="text-[var(--text-muted)] text-xs">I'll cite page numbers in my answers</p>
                </div>
                <div className="flex flex-col gap-2 w-full mt-2">
                  {['What is the main conclusion?', 'List the key recommendations', 'What are the risks mentioned?'].map((q) => (
                    <button
                      key={q}
                      onClick={() => { setInput(q); }}
                      className="text-xs text-left px-3 py-2 rounded-lg border border-[var(--border)] hover:border-[var(--border-hover)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-all"
                    >
                      {q}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {messages.map((msg, i) => (
              <div key={i} className={`flex gap-2 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                {msg.role === 'assistant' && (
                  <div className="w-7 h-7 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center flex-shrink-0 mt-1">
                    <Bot size={12} className="text-purple-400" />
                  </div>
                )}
                <div
                  className={`max-w-[80%] px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap ${
                    msg.role === 'user' ? 'chat-user' : 'chat-ai'
                  }`}
                >
                  {msg.content}
                </div>
                {msg.role === 'user' && (
                  <div className="w-7 h-7 rounded-xl bg-white/10 flex items-center justify-center flex-shrink-0 mt-1">
                    <User size={12} />
                  </div>
                )}
              </div>
            ))}

            {chatLoading && (
              <div className="flex gap-2 justify-start">
                <div className="w-7 h-7 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                  <Bot size={12} className="text-purple-400" />
                </div>
                <div className="chat-ai px-4 py-3">
                  <div className="flex gap-1.5 items-center">
                    {[0, 1, 2].map((i) => (
                      <div
                        key={i}
                        className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-bounce"
                        style={{ animationDelay: `${i * 0.15}s` }}
                      />
                    ))}
                  </div>
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          {/* Input */}
          <div className="flex gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && sendMessage()}
              placeholder="Ask a question…"
              disabled={chatLoading}
              className="flex-1 bg-white/[0.04] border border-[var(--border)] rounded-xl px-4 py-3 text-sm text-[var(--text-primary)] placeholder-[var(--text-muted)] outline-none focus:border-[var(--border-hover)] transition-colors disabled:opacity-50"
            />
            <button
              onClick={sendMessage}
              disabled={!input.trim() || chatLoading}
              className="px-4 py-3 rounded-xl bg-[var(--accent)] hover:bg-violet-500 disabled:opacity-40 disabled:cursor-not-allowed text-white transition-colors flex items-center justify-center"
            >
              <Send size={15} />
            </button>
          </div>
        </motion.div>
      </div>
    </main>
  );
}
